### ISSUE TITLE
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 503 Error:ServiceUnavailable The request has failed due to a temporary failure of the server

### ISSUE THREAD

**Issue by itexpertshire** [aliyun/aliyun-openapi-python-sdk#141]
Hi,

   I am struggling to resolve 503 error while using aliyun-python-sdk-edas module in below script.
Any hints or guidance for debugging is really appreciated.
```
# -*- coding: utf-8 -*-
import sys
from aliyunsdkcore.client import AcsClient
from aliyunsdkedas.request.v20170801 import QueryApplicationStatusRequest
from aliyunsdkedas.request.v20170801 import ListClusterRequest
from aliyunsdkedas.request.v20170801 import AuthorizeApplicationRequest
from aliyunsdkcore.request import CommonRequest
import uuid
from aliyunsdkcore.profile import region_provider
from aliyunsdkcore.http import method_type as MT
from aliyunsdkcore.http import format_type as FT


try:
    reload(sys)
    sys.setdefaultencoding('utf8')
except NameError:
    pass
except Exception as err:
    raise err


REGION = "cn-beijing"
PRODUCT_NAME = "Edas"
ENDPOINT = "edas.cn-beijing.aliyuncs.com"

MASTER_AK=''
MASTER_SK=''

region_provider.add_endpoint(PRODUCT_NAME, REGION, ENDPOINT)
acs_client = AcsClient(MASTER_AK, MASTER_SK, REGION)


def query_application():
    req = ListClusterRequest.ListClusterRequest()
    qappresponse = acs_client.do_action_with_exception(req)
    return qappresponse

if __name__ == '__main__':
    print(query_application())
```

Here is the error stack,

```
Traceback (most recent call last):
  File "EDASDemo.py", line 45, in <module>
    print(query_application())
  File "EDASDemo.py", line 37, in query_application
    qappresponse = acs_client.do_action_with_exception(req)
  File "D:\Amit\Soft\Python27\lib\site-packages\aliyunsdkcore\client.py", line 280, in do_action_with_exception
    request_id=request_id)
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 503 Error:ServiceUnavailable The request has failed due to a temporary failure of the
server. RequestID: CEB36D07-4C92-4146-B433-8C3C921615BA
```

**Comment by JacksonTian** [comment]
This 503 is a server side error, Need you submit a work order to get detail with request id(CEB36D07-4C92-4146-B433-8C3C921615BA)

**Comment by itexpertshire** [comment]
> This 503 is a server side error, Need you submit a work order to get detail with request id(CEB36D07-4C92-4146-B433-8C3C921615BA)

Thanks for your response. What do you mean by work order? Are you referring support ticket?

**Comment by JacksonTian** [comment]
Hi @itexpertshire , did you get any useful help?

**Comment by itexpertshire** [comment]
Hi @JacksonTian ,

         Got feedback from Aliababa cloud tech support that the EDAS API is not yet supported and it's under development.

Thanks
Amit
