### ISSUE TITLE
python 3.7 调用aliyunsdkcms DescribeMetricLast 报错

### ISSUE THREAD

**Issue by ydq870102** [aliyun/aliyun-openapi-python-sdk#262]
* **Python Version**: 3.7
* **aliyunsdkcore Version**: core-v3: 2.13.3 
* **API**: 7.0.3

在API控制台中已测试通过，自己的环境调用报错。

代码：
from aliyunsdkcore.client import AcsClient
from aliyunsdkcms.request.v20190101.DescribeMetricLastRequest import DescribeMetricLastRequest

if __name__ ==  "__main__":
    client = AcsClient('****', '******', 'cn-hangzhou')

    request = DescribeMetricLastRequest()
    request.set_accept_format('json')

    request.set_Namespace("acs_ecs_dashboard")
    request.set_MetricName("CPUUtilization")

    response = client.do_action_with_exception(request)
    # python2:  print(response)
    print(str(response, encoding='utf-8'))

错误信息:
Traceback (most recent call last):
  File "/home/ydq/PycharmProjects/HDOpsM3/apps/task/util.py", line 429, in <module>
    aliyun.collect_ecs_cpu_metric()
  File "/home/ydq/PycharmProjects/HDOpsM3/apps/task/util.py", line 370, in collect_ecs_cpu_metric
    response = clt.do_action(request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/client.py", line 447, in do_action
    status, headers, body, exception = self._implementation_of_do_action(acs_request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/client.py", line 283, in _implementation_of_do_action
    endpoint = self._resolve_endpoint(request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/client.py", line 441, in _resolve_endpoint
    return self._endpoint_resolver.resolve(resolve_request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/endpoint/default_endpoint_resolver.py", line 47, in resolve
    return self._resolver.resolve(request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/endpoint/chained_endpoint_resolver.py", line 68, in resolve
    endpoint = resolver.resolve(request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/endpoint/location_service_endpoint_resolver.py", line 61, in resolve
    return self._get_endpoint_from_location_service(key, request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/endpoint/location_service_endpoint_resolver.py", line 68, in _get_endpoint_from_location_service
    self._call_location_service(key, request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/endpoint/location_service_endpoint_resolver.py", line 97, in _call_location_service
    raise e
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/endpoint/location_service_endpoint_resolver.py", line 82, in _call_location_service
    response = self._client.do_action_with_exception(request)
  File "/usr/local/python3/lib/python3.7/site-packages/aliyunsdkcore/client.py", line 429, in do_action_with_exception
    raise exception
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 500 Error:InternalError The request processing has failed due to some unknown error, exception or failure. RequestID: D53DF6C8-819B-47C1-8C96-547A87374155

**Comment by wallisyan** [comment]
您好，我基于aliyunsdkcms 7.0.3版本，core-v3 2.13.3，未能复现您的问题。
此外，我看到您使用core-v3，我们做了core部分的兼容，不区分Python2/3版本，您可以`pip uninstall aliyun-python-sdk-core-v3`，然后`pip install aliyun-python-sdk-core` 获取最新版本的aliyunsdkcore 。
如以上不能解决您的问题，请告知。感谢您的反馈

**Comment by ydq870102** [comment]
已安装aliyun-python-sdk-core包，执行还是同样的报错。
Package                 Version      
----------------------- -------------
aliyun-python-sdk-cms   7.0.3        
aliyun-python-sdk-core  2.13.4       
aliyun-python-sdk-ecs   4.16.5

**Comment by JacksonTian** [comment]
@ydq870102 有 request id 的情况下，可以直接拿该值提工单：

 RequestID: D53DF6C8-819B-47C1-8C96-547A87374155
