### ISSUE TITLE
HTTP Status: 400 Error:InvalidDomainName.NoExist The specified domain name does not exist. Refresh the page and try again.

### ISSUE THREAD

**Issue by 007root** [aliyun/aliyun-openapi-python-sdk#316]
* **Python Version**: 3.6.9
* **aliyunsdkcore Version**: 2.13.15
* **API**: AddDomainBackupRequest

 
传参如下
```
client = AcsClient('L****K', 'd*****v', 'cn-hangzhou')

request = AddDomainBackupRequest()
request.set_accept_format('json')

request.set_DomainName("docker.*****.net")
request.set_PeriodType("HOUR")
response = client.do_action_with_exception(request)
print(str(response, encoding='utf-8'))
```
域名在管理页面是存在的, 但是调用接口报错
```
Traceback (most recent call last):
  File "/home/ubuntu/.vscode-server-insiders/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/ubuntu/.vscode-server-insiders/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/ubuntu/.vscode-server-insiders/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/d/virtualenv/test.py", line 23, in <module>
    response = client.do_action_with_exception(request)
  File "/mnt/d/virtualenv/aliyun/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 465, in do_action_with_exception
    raise exception
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 400 Error:InvalidDomainName.NoExist The specified domain name does not exist. Refresh the page and try again.
```
还请帮忙看一下
谢谢!!!

**Comment by JacksonTian** [comment]
这个问题请提一个工单。
