### ISSUE TITLE
Domain name resolution record addition has failed

### ISSUE THREAD

**Issue by barnettZQG** [aliyun/aliyun-openapi-python-sdk#389]
* **Python Version**: 3.6
* **aliyunsdkcore Version**:  aliyunsdkalidns.request.v20150109
* **API**:  
```
add = AddDomainRecordRequest.AddDomainRecordRequest()
        add.set_accept_format('json')
        add.add_query_param('DomainName', self.domain)
        add.add_query_param('RR', prefix_subdomain)
        add.add_query_param('Type', 'A')
        add.add_query_param('Value', ip)
        self.clt.do_action_with_exception(add)
```
error log: 
```
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 231, in implementation_of_do_action
30
status, headers, body = http_response.get_response_object()
31
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/http/http_response.py", line 71, in get_response_object
32
return self.get_http_response_object()
33
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/http/http_response.py", line 96, in get_http_response_object
34
self.__connection.connect()
35
File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
36
(self.host,self.port), self.timeout, self.source_address)
37
File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 77, in create_connection
38
for res in getaddrinfo(host, port, 0 if has_ipv6 else AF_INET, SOCK_STREAM):
39
File "/usr/local/lib/python3.6/site-packages/gevent/_socketcommon.py", line 288, in getaddrinfo
40
return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
41
File "/usr/local/lib/python3.6/site-packages/gevent/resolver_thread.py", line 65, in getaddrinfo
42
return self.pool.apply(_socket.getaddrinfo, args, kwargs)
43
File "/usr/local/lib/python3.6/site-packages/gevent/pool.py", line 325, in apply
44
return self.spawn(func, *args, **kwds).get()
45
File "/usr/local/lib/python3.6/site-packages/gevent/event.py", line 385, in get
46
return self.get(block=False)
47
File "/usr/local/lib/python3.6/site-packages/gevent/event.py", line 375, in get
48
return self._raise_exception()
49
File "/usr/local/lib/python3.6/site-packages/gevent/event.py", line 355, in _raise_exception
50
reraise(*self.exc_info)
51
File "/usr/local/lib/python3.6/site-packages/gevent/_compat.py", line 33, in reraise
52
raise value.with_traceback(tb)
53
File "/usr/local/lib/python3.6/site-packages/gevent/threadpool.py", line 211, in _worker
54
value = func(*args, **kwargs)
55
socket.gaierror: [Errno -3] Temporary failure in name resolution
56
During handling of the above exception, another exception occurred:
57
Traceback (most recent call last):
58
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
59
response = self.full_dispatch_request()
60
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
61
rv = self.handle_user_exception(e)
62
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
63
reraise(exc_type, exc_value, tb)
64
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
65
raise value
66
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
67
rv = self.dispatch_request()
68
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
69
return self.view_functions[rule.endpoint](**req.view_args)
70
File "/opt/domain/GRDomain/domain.py", line 43, in make_domain
71
if not domain and not dns.check_domain(prefix_subdomain=prefix_subdomain):
72
File "/opt/domain/GRDomain/utils.py", line 28, in check_domain
73
rst_chk = self.clt.do_action_with_exception(chk)
74
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 259, in do_action_with_exception
75
status, headers, body = self.implementation_of_do_action(acs_request)
76
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 236, in implementation_of_do_action
77
error_msg.get_msg('SDK_SERVER_UNREACHABLE') + ': ' + str(e))
78
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.ServerUnreachable Unable to connect server: [Errno -3] Temporary failure in name resolution
79
During handling of the above exception, another exception occurred:
80
Traceback (most recent call last):
81
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 56, in handle
82
self.handle_request(listener_name, req, client, addr)
83
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
84
super(GeventWorker, self).handle_request(*args)
85
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 107, in handle_request
86
respiter = self.wsgi(environ, resp.start_response)
87
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
88
return self.wsgi_app(environ, start_response)
89
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
90
response = self.handle_exception(e)
91
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1748, in handle_exception
92
return self.finalize_request(handler(e), from_error_handler=True)
93
File "/opt/domain/GRDomain/utils.py", line 128, in general_error
94
return render_template('errors/500.html', error=error.description), 500
95
AttributeError: 'ClientException' object has no attribute 'description'
96
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 231, in implementation_of_do_action
97
status, headers, body = http_response.get_response_object()
98
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/http/http_response.py", line 71, in get_response_object
99
return self.get_http_response_object()
100
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/http/http_response.py", line 96, in get_http_response_object
101
self.__connection.connect()
102
File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
103
(self.host,self.port), self.timeout, self.source_address)
104
File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 77, in create_connection
105
for res in getaddrinfo(host, port, 0 if has_ipv6 else AF_INET, SOCK_STREAM):
106
File "/usr/local/lib/python3.6/site-packages/gevent/_socketcommon.py", line 288, in getaddrinfo
107
return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
108
File "/usr/local/lib/python3.6/site-packages/gevent/resolver_thread.py", line 65, in getaddrinfo
109
return self.pool.apply(_socket.getaddrinfo, args, kwargs)
110
File "/usr/local/lib/python3.6/site-packages/gevent/pool.py", line 325, in apply
111
return self.spawn(func, *args, **kwds).get()
112
File "/usr/local/lib/python3.6/site-packages/gevent/event.py", line 385, in get
113
return self.get(block=False)
114
File "/usr/local/lib/python3.6/site-packages/gevent/event.py", line 375, in get
115
return self._raise_exception()
116
File "/usr/local/lib/python3.6/site-packages/gevent/event.py", line 355, in _raise_exception
117
reraise(*self.exc_info)
118
File "/usr/local/lib/python3.6/site-packages/gevent/_compat.py", line 33, in reraise
119
raise value.with_traceback(tb)
120
File "/usr/local/lib/python3.6/site-packages/gevent/threadpool.py", line 211, in _worker
121
value = func(*args, **kwargs)
122
socket.gaierror: [Errno -3] Temporary failure in name resolution
123
During handling of the above exception, another exception occurred:
124
Traceback (most recent call last):
125
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
126
response = self.full_dispatch_request()
127
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
128
rv = self.handle_user_exception(e)
129
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
130
reraise(exc_type, exc_value, tb)
131
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
132
raise value
133
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
134
rv = self.dispatch_request()
135
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
136
return self.view_functions[rule.endpoint](**req.view_args)
137
File "/opt/domain/GRDomain/domain.py", line 43, in make_domain
138
if not domain and not dns.check_domain(prefix_subdomain=prefix_subdomain):
139
File "/opt/domain/GRDomain/utils.py", line 28, in check_domain
140
rst_chk = self.clt.do_action_with_exception(chk)
141
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 259, in do_action_with_exception
142
status, headers, body = self.implementation_of_do_action(acs_request)
143
File "/usr/local/lib/python3.6/site-packages/aliyunsdkcore/client.py", line 236, in implementation_of_do_action
144
error_msg.get_msg('SDK_SERVER_UNREACHABLE') + ': ' + str(e))
145
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.ServerUnreachable Unable to connect server: [Errno -3] Temporary failure in name resolution
```

**Comment by barnettZQG** [comment]
域名解析不了导致。
