### ISSUE TITLE
SDK 报http request timeout

### ISSUE THREAD

**Issue by caiwei1995** [aliyun/aliyun-openapi-python-sdk#406]
* **Python Version**: 2.7.5
* **aliyunsdkcore Version**:aliyun_python_sdk_core-2.13.4
* **API**:getPageSlbInstances, 调用do_action_with_exception()
 
* **EXCEPTION**:
Traceback (most recent call last):
  File "XXXXXX", line 180, in getPageSlbInstances
    resps = c.do_action_with_exception(r_slb)
  File "/usr/lib/python2.7/site-packages/aliyunsdkcore/client.py", line 430, in do_action_with_exception
    status, headers, body, exception = self._implementation_of_do_action(acs_request)
  File "/usr/lib/python2.7/site-packages/aliyunsdkcore/client.py", line 285, in _implementation_of_do_action
    return self._handle_retry_and_timeout(endpoint, request, signer)
  File "/usr/lib/python2.7/site-packages/aliyunsdkcore/client.py", line 353, in _handle_retry_and_timeout
    raise exception
代码里timeout超时时间已经设置到了60s，但是还是会超时。

**Comment by 824750130** [comment]
可以ping通目标地址吗？
