### ISSUE TITLE
aliyun-python-sdk-core can not install

### ISSUE THREAD

**Issue by THtianhao** [aliyun/aliyun-openapi-python-sdk#519]
您好我是写了一个Comfyui的插件叫 https://github.com/THtianhao/ComfyUI-Portrait-Maker，很多windows用户出现一个问题，我的windows用户安装modelscope包的时候依赖于aliyun-python-sdk-core 出现下面的错误：
```
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached aliyun-python-sdk-core-2.13.36.tar.gz (440 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\albam\AppData\Local\Temp\pip-install-025cd5tn\aliyun-python-sdk-core_78b82f9b135341b1a2825e5884118385\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]
```
不仅仅是我遇到了这样的问题，使用ComfyUI的用户只要是windows用户，使用了ComfyUI的整合包（https://github.com/comfyanonymous/ComfyUI/releases）有依赖于aliyun-python-sdk-core 的，都会出现pip安装不了的情况，也咨询了ComfyUI的作者，作者给出的解决方案也解决不了 如下https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/223
请阿里的大神们帮忙看看，毕竟这个问题不在少数，我在Stable-diffusion-webui的issue里面也看到过类似的问题，都是无法解决

* **Python Version**:3.10.11
* **aliyunsdkcore Version**:modelscope 1.9.2
* **API**:aliyun-python-sdk-core

**Comment by tietang** [comment]
是的只要是使用了python_embeded就无法安装，但直接使用pip安装没问题

**Comment by yueyinqiu** [comment]
一样碰到了，尝试了先安装

```
.\python_embeded\python -m pip install opendatalab==0.0.9
.\python_embeded\python -m pip install openmim
```

再安装好像就可以了。不清楚为什么，从这里看到的：https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/84#issuecomment-1670749516

**Comment by jiandanplus** [comment]
解决了吗老铁，写个插件，卡这里两天了
